# Prometheus configuration file

global:
  scrape_interval: 15s  # Default scrape interval
  evaluation_interval: 15s  # Default evaluation interval for rules

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scraping the Prometheus instance itself

  # Example: You can add more scrape configs for other services here
  # - job_name: 'my-app'
  #   static_configs:
  #     - targets: ['my-app-service:8080']
  #     - targets: ['another-service:9090']

# Alerts configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']  # Default Alertmanager instance

# Rule configuration
rule_files:
  - "first_rules.yml"
  - "second_rules.yml"

# Additional scrape configurations can go here, such as for exporters
# - job_name: 'node_exporter'
#   static_configs:
#     - targets: ['localhost:9100']
